### ISSUE TITLE
Problem installing plugin.

### ISSUE THREAD

**Issue by a930334** [frontyard/cordova-plugin-exoplayer#49]
Hi,

When i try to install the plugin, I get the next error:

------------------------------------------------------------------------------------
Failed to install 'cordova-plugin-exoplayer': CordovaError: Uh oh!
"/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/plugins/cordova-plugin-exoplayer/www/ExoPlayer.js" not found!
    at copyFile (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/lib/pluginHandlers.js:219:36)
    at install (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/lib/pluginHandlers.js:146:13)
    at Object.process (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/Api.js:243:74
    at _fulfilled (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/platforms/android/cordova/node_modules/q/q.js:624:44

(node:19300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Uh oh!
"/home/jcarlos/Documentos/proyectos_jc/ionic/LacAPPfetera/plugins/cordova-plugin-exoplayer/www/**ExoPlayer.js**" not found!

------------------------------------------------------------------------------------

There isn't a file called ExoPlayer.js but exoplayer.js, whitout uppercase.

Regards

**Comment by a930334** [comment]
I have not this problem when I install 2.5.0. version. 

That's what i get when i Run "ionic info"

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 browser 5.0.3 ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.12.3
    npm               : 3.10.10 
    OS                : Linux 4.14

Environment Variables:

    ANDROID_HOME : /home/jcarlos/Android/Sdk

Misc:

    backend : legacy

**Comment by frontyard** [comment]
That has been fixes a while back. You need to be using latest release which is 2.5.3

https://github.com/frontyard/cordova-plugin-exoplayer/pull/41

**Comment by TadeoArmenta** [comment]
i've problems too

`Installing "cordova-plugin-exoplayer" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-exoplayer': CordovaError: Uh oh!
"/root/yourtv/android/platforms/android/app/src/main/res/values/ids.xml" already exists!
    at copyNewFile (/root/yourtv/android/platforms/android/cordova/lib/pluginHandlers.js:261:45)
    at install (/root/yourtv/android/platforms/android/cordova/lib/pluginHandlers.js:51:17)
    at ActionStack.process (/root/yourtv/android/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/root/yourtv/android/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/root/yourtv/android/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /root/yourtv/android/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/root/yourtv/android/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/root/yourtv/android/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/root/yourtv/android/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /root/yourtv/android/platforms/android/cordova/node_modules/q/q.js:570:49
(node:16073) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Uh oh!
"/root/yourtv/android/platforms/android/app/src/main/res/values/ids.xml" already exists!
(node:16073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

@frontyard  any clue ?

`cordova : 8.0.0.0
 Node:  v9.1.0
 npm: 5.6.0`
