### ISSUE TITLE
Ionic 3 + ExoPlayer

### ISSUE THREAD

**Issue by RhuanGonzaga** [frontyard/cordova-plugin-exoplayer#59]
ExoPlayer is not working on Ionic 3, I'm using this code:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Platform } from 'ionic-angular';
declare var ExoPlayer;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, public plt: Platform) {
  }
	play() {
	  var params = { 
			url: 'http://static.videogular.com/assets/videos/videogular.mp4',
			aspectRatio: 'FIT_SCREEN', // default is FIT_SCREEN
			autoplay: true,
			seekTo: 0, // Start playback 10 minutes into video specified in milliseconds, default is 0
			controller: { // If this object is not present controller will not be visible
					hideProgress: false,
          hidePosition: false, // If timebar is visible hide current position from it
          hideDuration: false, // If timebar is visible Hide stream duration from it
					controlIcons: {
			
					}
			}
		}
		this.plt.ready().then(() => {
			  // ExoPlayer.show(params, (msg)=>console.log(msg), (err)=>console.log(err));
        ExoPlayer.show(params);
    });
  }
}
```

Android Error:

```
05-16 17:29:17.434 8483-8483/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: io.ionic.starter, PID: 8483
                                                                java.lang.StringIndexOutOfBoundsException: length=0; index=0
                                                                    at java.lang.String.charAt(Native Method)
                                                                    at android.graphics.Color.parseColor(Color.java:147)
                                                                    at co.frontyard.cordova.plugin.exoplayer.LayoutProvider.setupButtons(LayoutProvider.java:101)
                                                                    at co.frontyard.cordova.plugin.exoplayer.LayoutProvider.setupController(LayoutProvider.java:68)
                                                                    at co.frontyard.cordova.plugin.exoplayer.LayoutProvider.getExoPlayerView(LayoutProvider.java:61)
                                                                    at co.frontyard.cordova.plugin.exoplayer.Player.createDialog(Player.java:228)
                                                                    at co.frontyard.cordova.plugin.exoplayer.Player.createPlayer(Player.java:206)
                                                                    at co.frontyard.cordova.plugin.exoplayer.Plugin$1.run(Plugin.java:46)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

Ionic Info:

```
cli packages: (C:\Users\1513 IRON\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.5.3

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.1
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Android\sdk

Misc:

    backend : legacy
```

Default Plugins:

```
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-exoplayer 2.5.4 "ExoPlayer"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

My android emulator runs Android 7.0 (API 24), thank you so much!
Ps: If I remove controller object from code I can run videos but without control buttons (play, pause, forward...)

Tks!

**Comment by frontyard** [comment]
Try adding buttonsColor: '#ffffff' to the controller object.

**Comment by Dilipjp** [comment]
try this
 buttonsColor: '#ffff0000', // This example uses hex values including alpha (first byte)

**Comment by zeroxies90** [comment]
How can I play video in Ionic 5 angular12 , I am using Capacitor android and @ionic-native/android-exoplayer and after build apk its not showing player view

that I have

this.androidExoPlayer.show({
url: url,
controller: { // If this object is not present controller will not be visible
streamImage: 'https://i.imgur.com/FOwNemD.png',
streamTitle: 'Entretenimiento',
streamDescription: 'Channel',
hidePosition: false,
hideDuration: false
}

});
